### ISSUE TITLE
Glitches for Elgg2.0 version

### ISSUE THREAD

**Issue by robleegutierrez** [iionly/elggx_userpoints#3]
Hi iionly,

I love your plugins and work for elgg. I want report some glitches that could possibly be fixed in a future update if you ever want to update the plugin.
- **Adding Friends** - Users found a glitch to keep adding the same person hundreds of times. As a result, abusing the system.
  **Quick Solution:** Revoke users from earning from this task by setting zero.
- **Likes** - Users found a glitch to keep liking the same post hundreds of times resulting the same abuse as stated above.
  **Quick Solution:** Disable from earning as stated above.

I would love to reward my users with these features, but it is just being abused at the moment if enabled.

Best Regards,
Robert G.

**Comment by iionly** [comment]
I'm currently working on the Userpoints plugin already trying to come up with fixes for these two issues among other things.

**Comment by iionly** [comment]
Sorry it took so long... Fixed in 2.3.2 release.
