### ISSUE TITLE
Add points to interact with posts

### ISSUE THREAD

**Issue by AbdulazizSobh** [iionly/elggx_userpoints#7]
Is it possible to specify the addition of points to the interaction with the participation, such as if a member posted something and the post was liked or given the post to be evaluated by the rest of the members

**Comment by iionly** [comment]
Sorry. But I have no idea what you are asking for.

It's already possible to award points to the member who added the content and also to the members who post comments, or like these entries. With the Fivestar plugin available it's also possible to award points to members who rate content. I don't know what other response to content could be awarded with points.

**Comment by AbdulazizSobh** [comment]
thanks for replying
What I mean, like Reddit, you can have karma when members vote on posts
This is what I mean in addition to getting points like when someone likes a post
